name = "drive"
type = "webpack"
workers_dev = true
account_id = "9d2e48f5c41e59406667870acadb19da"
zone_id = "00973d128ce47a67d209f5e35760fb28"
kv_namespaces = [
    { binding = "BUCKET", id = "35d372bf4cf6476887cb8f8256210263" }
]

[env.staging]
name = "drive-staging"
